# Generated by Django 5.2.5 on 2025-08-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.IntegerField(unique=True)),
                ("pair_id", models.CharField(max_length=40, unique=True)),
                (
                    "pool_contracts",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mapping of exchange IDs to their pool contract addresses",
                    ),
                ),
                ("base_token", models.CharField(max_length=20)),
                ("quote_token", models.CharField(max_length=20)),
                ("base_token_decimals", models.IntegerField(default=18)),
                ("quote_token_decimals", models.IntegerField(default=18)),
                (
                    "active_exchanges",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of exchange IDs where this pair is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["uid"],
            },
        ),
    ]
